before_script:
  - julia -e 'versioninfo()'

variables:
  JULIA_PKGDIR: "$CI_PROJECT_DIR/.julia/"
  package: 'CLBLAS'

stages:
  - test
  - postprocess


## testing

.test_template: &pkg2_test_template
  script:
    - julia -e "Pkg.init();
                symlink(\"$CI_PROJECT_DIR\", joinpath(Pkg.dir(), \"$package\"));
                Pkg.resolve();
                Pkg.build(\"$package\");
                Pkg.test(\"$package\"; coverage=true)"
  artifacts:
    paths:
      - .julia/
      - deps/ext.jl
      - src/*.cov
      - src/*/*.cov # gitlab-runner#2620

test:v0.6:
  stage: test
  image: juliagpu/julia:v0.6
  <<: *pkg2_test_template


## post-processing
