language: julia

os:
  - linux

julia:
  - release
  - nightly

env:
  - CLBLAS=2.6 PATCH=0
  - CLBLAS=2.8 PATCH=0

notifications:
  email: false

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
    packages:
      - llvm-3.7-dev
      - llvm-3.7
      - ocl-icd

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      export POCL=pocl-0.12;
      export AMDAPPSDKROOT=${HOME}/opencl;
      mkdir -p ${AMDAPPSDKROOT};

      wget http://portablecl.org/downloads/${POCL}.tar.gz;
      tar -xf ${POCL}.tar.gz;
      cd ${POCL};
      cmake . -DCMAKE_INSTALL_PREFIX:PATH=${AMDAPPSDKROOT};
      make install;

      export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors;
      export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib:${LD_LIBRARY_PATH};
    fi;
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      wget https://github.com/clMathLibraries/clBLAS/releases/download/v${CLBLAS}/clBLAS-${CLBLAS}.${PATCH}-Linux-x64.tar.gz;
      tar -xf clBLAS-${CLBLAS}.${PATCH}-Linux-x64.tar.gz;
      echo ${TRAVIS_BUILD_DIR};
      export LD_LIBRARY_PATH=${HOME}/build/JuliaGPU/CLBLAS.jl/clBLAS-${CLBLAS}.${PATCH}-Linux-x64/lib64:${LD_LIBRARY_PATH};
    fi;

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.checkout("OpenCL");'
  - julia -e 'using CLBLAS; @assert isdefined(:CLBLAS); @assert typeof(CLBLAS) === Module'
  - julia -e 'Pkg.test("CLBLAS")'

# after_success:
#   - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
