language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly

notifications:
  email: false

sudo: false

git:
  depth: 9999999

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
    fi;
