language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get update -qq -y;
      sudo apt-get install -qq fglrx opencl-headers;
      wget https://github.com/clMathLibraries/clBLAS/releases/download/v2.6/clBLAS-2.6.0-Linux-x64.tar.gz;
      tar -xf clBLAS-2.6.0-Linux-x64.tar.gz;
      export LD_LIBRARY_PATH=/home/travis/build/JuliaGPU/CLBLAS.jl/clBLAS-2.6.0-Linux-x64/lib64:${LD_LIBRARY_PATH};
    fi;
  # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - julia -e 'Pkg.add("OpenCL"); Pkg.checkout("OpenCL")'
  - julia -e 'Pkg.add("CLBLAS"); Pkg.checkout("CLBLAS")'
  # - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("CLBLAS"))`); Pkg.pin("CLBLAS"); Pkg.resolve()'
  - julia test/runtests.jl
