language: julia
os:
  - linux
  #- osx
julia:
  - release
notifications:
  email: false
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get update -qq -y;
      sudo apt-get install -qq fglrx opencl-headers;
    fi;
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p deps/
  - cd deps/
  - git clone https://github.com/clMathLibraries/clBLAS
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p bin/clBLAS
  - cd bin/clBLAS
  - cmake -DBoost_NO_SYSTEM_PATHS=OFF ${TRAVIS_BUILD_DIR}/deps/clBLAS/src
  - make 
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/bin/clBLAS/library:${LD_LIBRARY_PATH}
  
script:
  - cd ${TRAVIS_BUILD_DIR}
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("CLBLAS"))`); Pkg.pin("CLBLAS"); Pkg.resolve()'
  - julia -e 'using CLBLAS; @assert isdefined(:CLBLAS); @assert typeof(CLBLAS) === Module'
  - julia -e 'import CLBLAS; CLBLAS.setup()'
  - julia examples/clblasSscal.jl 
  - julia examples/clblasSscal_alt.jl
  - julia examples/clblasSscal_future.jl
  - julia examples/clblasSasum.jl
  - julia examples/clblasSswap.jl
  - julia examples/clblasSaxpy.jl
  - julia examples/clblasSdot.jl
  - julia examples/clblasSnrm2.jl
  - julia examples/clblasiSamax.jl
  - julia examples/clblasSgemm_future.jl
  #- julia examples/clblasSgemmRandomBufferFuture.jl
